### ISSUE TITLE
make erro

### ISSUE THREAD

**Issue by jack338c** [kuoruan/luci-app-qos-gargoyle#1]
Dear kuoruan
thanks for shareing this repository
but I can't make it,please help

jack@jack-R478-R429:~/ledemaster/source$ make menuconfig
ERROR: please fix package/luci-app-qos-gargoyle/Makefile - see logs/package/luci-app-qos-gargoyle/dump.txt for details
Collecting package info: done

in dump.txt:
Makefile:30: ../../luci.mk: No such file or directory
make[2]: *** No rule to make target '../../luci.mk'.  Stop.

**Comment by jack338c** [comment]
still have problem
I copy patch to /source/target/linux/generic/patches-4.4/
but I did not find luci-app-qos-gargoyle after make menuconfig
please help

**Comment by kuoruan** [comment]
You should copy luci-app-qos-gargoyle to ```feeds/luci/application/```
then
```
rm -rf ./tmp
./scripts/feeds update luci
./scripts/feeds install luci
```

**Comment by kuoruan** [comment]
This is for my own repo, so the directory structure is strange.
https://github.com/kuoruan/lede-luci/tree/master/applications
If you want to use this LuCI, you should patch your OpenWrt/LEDE with https://github.com/kuoruan/lede/blob/master/target/linux/generic/patches-4.4/991-netfilter_add_imq_support.patch and some other changes.
If you want compile this, you can try use my fork https://github.com/kuoruan/lede

**Comment by jack338c** [comment]
thanks a lot Kuoruan,

here are my steps in my lede master tree for your luci-app-qos-gargoyle
1.git clone https://github.com/kuoruan/qos-gargoyle.git to /home/jack/ledemaster/source/package/feeds
2.git clone https://github.com/kuoruan/luci-app-qos-gargoyle.git to feeds/luci/application/ 
3.wget https://github.com/kuoruan/lede/blob/master/target/linux/generic/patches-4.4/991-netfilter_add_imq_support.patch to /source/target/linux/generic/patches-4.4/
4.rm -rf ./tmp ,./scripts/feeds update luci && ./scripts/feeds install luci
5.make menuconfig 
but I sitll can not find luci-app-qos-gargoyle

by the way I have intereting on your fork https://github.com/kuoruan/lede

and could you add luci-amule( https://github.com/openwrt-stuff/openwrt-extra/tree/master/luci/applications) to your fork in the future.that's will be perfect !

**Comment by jack338c** [comment]
already slove it
thanks again

**Comment by jack338c** [comment]
make erro again,did I miss something?


jack@jack-R478-R429:~/ledemaster/source$ make -j1 V=s
make[1]: Entering directory '/home/jack/ledemaster/source'
make[2]: Entering directory '/home/jack/ledemaster/source'
make[3]: Entering directory '/home/jack/ledemaster/source/target/linux'
make[4]: Entering directory '/home/jack/ledemaster/source/target/linux/ar71xx'
rm -rf /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand
mkdir -p /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand
xzcat /home/jack/ledemaster/source/dl/linux-4.4.70.tar.xz | tar -C /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand -xf -
cp -fpR "/home/jack/ledemaster/source/target/linux/generic/files"/. "/home/jack/ledemaster/source/target/linux/ar71xx/files"/. /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand/linux-4.4.70/
find /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand/linux-4.4.70/ -name \*.rej -or -name \*.orig | xargs -r rm -f

Applying /home/jack/ledemaster/source/target/linux/generic/patches-4.4/001-mtdsplit_backport.patch using plaintext: 
patching file drivers/mtd/mtdsplit/mtdsplit_brnimage.c
patching file drivers/mtd/mtdsplit/mtdsplit_eva.c
patching file drivers/mtd/mtdsplit/mtdsplit_fit.c
patching file drivers/mtd/mtdsplit/mtdsplit_lzma.c
patching file drivers/mtd/mtdsplit/mtdsplit_seama.c
patching file drivers/mtd/mtdsplit/mtdsplit_squashfs.c
patching file drivers/mtd/mtdsplit/mtdsplit_tplink.c
patching file drivers/mtd/mtdsplit/mtdsplit_trx.c
patching file drivers/mtd/mtdsplit/mtdsplit_uimage.c
patching file drivers/mtd/mtdsplit/mtdsplit_wrgg.c

Applying /home/jack/ledemaster/source/target/linux/generic/patches-4.4/001-musl-fixes.patch using plaintext: 
patching file Makefile
Hunk #1 FAILED at 21.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
can't find file to patch at input line 14
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/qosmon.c
|+++ b/qosmon.c
--------------------------
No file to patch.  Skipping patch.
3 out of 3 hunks ignored
Patch failed!  Please fix /home/jack/ledemaster/source/target/linux/generic/patches-4.4/001-musl-fixes.patch!
Makefile:24: recipe for target '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand/linux-4.4.70/.prepared_1bd22755b6ddbe81cc71e04c704899fe' failed
make[4]: *** [/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand/linux-4.4.70/.prepared_1bd22755b6ddbe81cc71e04c704899fe] Error 1
make[4]: Leaving directory '/home/jack/ledemaster/source/target/linux/ar71xx'
Makefile:13: recipe for target 'compile' failed
make[3]: *** [compile] Error 2
make[3]: Leaving directory '/home/jack/ledemaster/source/target/linux'
target/Makefile:23: recipe for target 'target/linux/compile' failed
make[2]: *** [target/linux/compile] Error 2
make[2]: Leaving directory '/home/jack/ledemaster/source'
target/Makefile:18: recipe for target '/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.target_compile' failed
make[1]: *** [/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/jack/ledemaster/source'
/home/jack/ledemaster/source/include/toplevel.mk:206: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by kuoruan** [comment]
001-musl-fixes.patch is for qos-gargoyle only
not for lede.
put https://github.com/kuoruan/qos-gargoyle in your package dir

**Comment by jack338c** [comment]
I put that to my package dir 

now I try make package/luci-app-qos-gargoyle/compile V=s
here is the logs
......
e/staging_dir/target-mips_24kc_musl/lib -L/home/jack/ledemaster/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl/usr/lib -L/home/jack/ledemaster/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl/lib -znow -zrelro -L /home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/usr/lib" BUILD_DIR="/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl" all
make[3]: Entering directory '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle'
mips-openwrt-linux-musl-gcc -D ONLYBG -D_GNU_SOURCE -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle:qos-gargoyle -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I /home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/usr/include -I /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full/iproute2-4.11.0 /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full/iproute2-4.4.0/include -I /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full/iproute2-4.11.0 /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full/iproute2-4.4.0/tc -c qosmon.c -o qosmon.o
qosmon.c:40:19: fatal error: utils.h: No such file or directory
compilation terminated.
Makefile:24: recipe for target 'qosmon.o' failed
make[3]: *** [qosmon.o] Error 1
make[3]: Leaving directory '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle'
Makefile:68: recipe for target '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle/.built' failed
make[2]: *** [/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle/.built] Error 2
make[2]: Leaving directory '/home/jack/ledemaster/source/package/qos-gargoyle'
package/Makefile:109: recipe for target 'package/qos-gargoyle/compile' failed
make[1]: *** [package/qos-gargoyle/compile] Error 2
make[1]: Leaving directory '/home/jack/ledemaster/source'
/home/jack/ledemaster/source/include/toplevel.mk:206: recipe for target 'package/luci-app-qos-gargoyle/compile' failed
make: *** [package/luci-app-qos-gargoyle/compile] Error 2

**Comment by kuoruan** [comment]
That's because you have 2 version of iproute2,
```rm -rf /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full```
then retry.

**Comment by jack338c** [comment]
Now make package/luci-app-qos-gargoyle/compile V=s is successful

but when I try make -j 3  sitll have problem


....
Applying /home/jack/ledemaster/source/target/linux/generic/patches-4.4/922-always-create-console-node-in-initramfs.patch using plaintext: 
patching file scripts/gen_initramfs_list.sh

Applying /home/jack/ledemaster/source/target/linux/generic/patches-4.4/930-crashlog.patch using plaintext: 
patching file include/linux/crashlog.h
patching file init/Kconfig
patching file kernel/Makefile
patching file kernel/crashlog.c
patching file kernel/module.c
patching file mm/memblock.c
patching file mm/bootmem.c

Applying /home/jack/ledemaster/source/target/linux/generic/patches-4.4/970-remove-unsane-filenames-from-deps_initramfs-list.patch using plaintext: 
patching file usr/Makefile

Applying /home/jack/ledemaster/source/target/linux/generic/patches-4.4/991-netfilter_add_imq_support.patch using plaintext: 
patch: **** Only garbage was found in the patch input.
Patch failed!  Please fix /home/jack/ledemaster/source/target/linux/generic/patches-4.4/991-netfilter_add_imq_support.patch!
Makefile:24: recipe for target '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand/linux-4.4.70/.prepared_3055b8a919fda718c7734a373181fa3f' failed
make[4]: *** [/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand/linux-4.4.70/.prepared_3055b8a919fda718c7734a373181fa3f] Error 1
make[4]: Leaving directory '/home/jack/ledemaster/source/target/linux/ar71xx'
Makefile:13: recipe for target 'compile' failed
make[3]: *** [compile] Error 2
make[3]: Leaving directory '/home/jack/ledemaster/source/target/linux'
target/Makefile:23: recipe for target 'target/linux/compile' failed
make[2]: *** [target/linux/compile] Error 2
make[2]: Leaving directory '/home/jack/ledemaster/source'
target/Makefile:18: recipe for target '/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.target_compile' failed
make[1]: *** [/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/jack/ledemaster/source'
/home/jack/ledemaster/source/include/toplevel.mk:206: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by kuoruan** [comment]
Your 991-netfilter_add_imq_support.patch is broken.

**Comment by jack338c** [comment]
I trid del it and make clean 
then  wget https://github.com/kuoruan/lede/blob/master/target/linux/generic/patches-4.4/991-netfilter_add_imq_support.patch to /source/target/linux/generic/patches-4.4/  again

but still does not work

Applying /home/jack/ledemaster/source/target/linux/generic/patches-4.4/930-crashlog.patch using plaintext: 
patching file include/linux/crashlog.h
patching file init/Kconfig
patching file kernel/Makefile
patching file kernel/crashlog.c
patching file kernel/module.c
patching file mm/memblock.c
patching file mm/bootmem.c

Applying /home/jack/ledemaster/source/target/linux/generic/patches-4.4/970-remove-unsane-filenames-from-deps_initramfs-list.patch using plaintext: 
patching file usr/Makefile

Applying /home/jack/ledemaster/source/target/linux/generic/patches-4.4/991-netfilter_add_imq_support.patch using plaintext: 
patch: **** Only garbage was found in the patch input.
Patch failed!  Please fix /home/jack/ledemaster/source/target/linux/generic/patches-4.4/991-netfilter_add_imq_support.patch!
Makefile:24: recipe for target '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand/linux-4.4.70/.prepared_3055b8a919fda718c7734a373181fa3f' failed
make[4]: *** [/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand/linux-4.4.70/.prepared_3055b8a919fda718c7734a373181fa3f] Error 1
make[4]: Leaving directory '/home/jack/ledemaster/source/target/linux/ar71xx'
Makefile:13: recipe for target 'compile' failed
make[3]: *** [compile] Error 2
make[3]: Leaving directory '/home/jack/ledemaster/source/target/linux'
target/Makefile:23: recipe for target 'target/linux/compile' failed
make[2]: *** [target/linux/compile] Error 2
make[2]: Leaving directory '/home/jack/ledemaster/source'
target/Makefile:18: recipe for target '/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.target_compile' failed
make[1]: *** [/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/jack/ledemaster/source'
/home/jack/ledemaster/source/include/toplevel.mk:206: recipe for target 'world' failed
make: *** [world] Error 2
jack@jack-R478-R429:~/ledemaster/source$

**Comment by kuoruan** [comment]
Please use this url 
https://raw.githubusercontent.com/kuoruan/lede/master/target/linux/generic/patches-4.4/991-netfilter_add_imq_support.patch

**Comment by jack338c** [comment]
after rewget the new patch from you,everythig is ok but still have erro
here is the log
.....
Configuring coreutils-nohup.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for qos-gargoyle:
 * 	iptables-mod-imq * 
 * opkg_install_cmd: Cannot install package qos-gargoyle.
 * pkg_alternatives_update_path: failed symlinking /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/root-ar71xx/sbin/ip -> /sbin/ip-full
package/Makefile:64: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/jack/ledemaster/source'
package/Makefile:106: recipe for target '/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.package_install' failed
make[1]: *** [/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/jack/ledemaster/source'
/home/jack/ledemaster/source/include/toplevel.mk:206: recipe for target 'world' failed
make: *** [world] Error 2
jack@jack-R478-R429:~/ledemaster/source$

**Comment by kuoruan** [comment]
See this commit https://github.com/kuoruan/lede/commit/5f527aa1442007ad6e92f9812731508ff0b09830
You should also patch iptables and netfilter

**Comment by jack338c** [comment]
Ok,So I should copy netfilter.mk and iptables (folder) from https://github.com/kuoruan/lede.git and overwrite to my lede tree ,is that right?
thanks for your continuous support,I can't make it without your help

**Comment by kuoruan** [comment]
Do not forget the patch file.

**Comment by jack338c** [comment]
# **skip this** unfortunately ,worng again,modules/netfilter.mk:7: *** missing separator.  Stop. **# sorry my mistaken**

SHELL= flock /home/jack/ledemaster/source/tmp/.root-copy.flock -c 'cp -fpR /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/netifd-2017-05-22-7573880a/.pkgdir/netifd/. /home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/root-ar71xx/'
touch /home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/root-ar71xx/stamp/.netifd_installed
echo "netifd" >> /home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/pkginfo/netifd.default.install
make[3]: Leaving directory '/home/jack/ledemaster/source/package/network/config/netifd'
make[3]: Entering directory '/home/jack/ledemaster/source/package/firmware/linux-firmware'
make[3]: Nothing to be done for 'compile'.
make[3]: Leaving directory '/home/jack/ledemaster/source/package/firmware/linux-firmware'
make[3]: Entering directory '/home/jack/ledemaster/source/package/kernel/linux'
modules/netfilter.mk:7: *** missing separator.  Stop.
make[3]: Leaving directory '/home/jack/ledemaster/source/package/kernel/linux'
package/Makefile:109: recipe for target 'package/kernel/linux/compile' failed
make[2]: *** [package/kernel/linux/compile] Error 2
make[2]: Leaving directory '/home/jack/ledemaster/source'
package/Makefile:105: recipe for target '/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jack/ledemaster/source'
/home/jack/ledemaster/source/include/toplevel.mk:206: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by jack338c** [comment]
after put iptables folder and netfilter.mk my lede tree,still got same erro

  Configuring ppp-mod-pppoe.
Configuring coreutils-nohup.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for qos-gargoyle:
 * 	iptables-mod-imq * 
 * opkg_install_cmd: Cannot install package qos-gargoyle.
 * pkg_alternatives_update_path: failed symlinking /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/root-ar71xx/sbin/ip -> /sbin/ip-full
package/Makefile:64: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/jack/ledemaster/source'
package/Makefile:106: recipe for target '/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.package_install' failed
make[1]: *** [/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/jack/ledemaster/source'
/home/jack/ledemaster/source/include/toplevel.mk:206: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by kuoruan** [comment]
https://github.com/kuoruan/lede/blob/master/package/network/utils/iptables/Makefile
and
https://github.com/kuoruan/lede/blob/master/package/network/utils/iptables/patches/999-add-imq-support.patch

**Comment by jack338c** [comment]
1-4 which one please?



PILE="mips-openwrt-linux-musl-" ARCH="mips" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Fri May 26 22:48:37 2017" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/jack/ledemaster/source/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KERNELRELEASE=4.4.70 CC="mips-openwrt-linux-musl-gcc" modules
make[5]: Entering directory '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/linux-ar71xx_nand/linux-4.4.70'
scripts/kconfig/conf  --silentoldconfig Kconfig
net/sched/Kconfig:44: warning: menuconfig statement without prompt
*
* Restart config...
*
*
* Network device support
*
Network device support (NETDEVICES) [Y/n/?] y
  Network core driver support (NET_CORE) [Y/n/?] y
    Bonding driver support (BONDING) [N/m/y/?] n
    Dummy net driver support (DUMMY) [N/m/y/?] n
    EQL (serial line load balancing) support (EQUALIZER) [N/m/y/?] n
    Fibre Channel driver support (NET_FC) [N/y/?] n
    Intermediate Functional Block support (IFB) [M/n/y/?] m
    MAC-VLAN support (MACVLAN) [N/m/y/?] n
    IP-VLAN support (IPVLAN) [N/m/y/?] n
    Virtual eXtensible Local Area Network (VXLAN) (VXLAN) [N/m/y/?] n
    Network console logging support (NETCONSOLE) [N/m/y/?] n
    IMQ (intermediate queueing device) support (IMQ) [M/y/?] m
      IMQ behavior (PRE/POSTROUTING)
        1. IMQ AA (IMQ_BEHAVIOR_AA) (NEW)
      > 2. IMQ AB (IMQ_BEHAVIOR_AB) (NEW)
        3. IMQ BA (IMQ_BEHAVIOR_BA) (NEW)
        4. IMQ BB (IMQ_BEHAVIOR_BB) (NEW)
      choice[1-4?]:

**Comment by kuoruan** [comment]
Just use default..

**Comment by jack338c** [comment]
awesome ! it works!! thank you very much !!!

**Comment by jack338c** [comment]
is that-- unknown option "--todev"  ok? ,please help  Koruan,thank you

/etc/init.d/qos_gargoyle restart
........
+ iptables -t mangle -I qos_ingress -j MARK --set-mark 0x400
+ iptables -t mangle -I qos_ingress -m mark ! --mark 0x0 -j RETURN
+ iptables -t mangle -I qos_ingress -m mark ! --mark 0x0 -j CONNMARK --save-mark --mask 0x7F00
+ iptables -t mangle -I qos_ingress -j IMQ --todev 0
iptables v1.6.1: unknown option "--todev"
Try `iptables -h' or 'iptables --help' for more information.
+ iptables -t mangle -A qos_ingress -j CONNMARK --save-mark --mask 0x7F00
+ set +x


I found this https://jira.untangle.com/browse/NGFW-10209
so qos_gargoyle is not working ?

**Comment by kuoruan** [comment]
Did you patch your iptables?
https://github.com/kuoruan/lede/raw/master/package/network/utils/iptables/patches/999-add-imq-support.patch

打上这个补丁就行了！

**Comment by jack338c** [comment]
Ok,I got it
thank you !

**Comment by jack338c** [comment]
I rebuid it again,but it still get unknown option "--todev" when I do "/etc/init.d/qos_gargoyle restart"
here are my steps
1.first built a firmware without qos_gargoyle ,after make successfuly ,then add qos_gargoyle package and its luci to my local lede source tree

2.copy makefile and 999-add-imq-support.patch to /source/package/network/utils/iptables  

3.copy 991-netfilter_add_gargoyle_imq.patch to  /source/target/linux/generic/patches-4.4/
4.copy netfilter.mk to  /source/package/kernel/linux/modules/
5.add CONFIG_IMQ_BEHAVIOR_BA=y to target/linux/generic/config-4.4
6.make -j1 V=s ,then choise 3 for MQ_BEHAVIOR_BA

**Comment by kuoruan** [comment]
Pls make sure iptables-mod-imq is selected in ```make menuconfig```

**Comment by jack338c** [comment]
I just checked , it's selected

**Comment by kuoruan** [comment]
```
make package/iptables/clean
make package/iptables/compile V=s
```
Try clean and recompile

**Comment by jack338c** [comment]
it did not work
maybe I should  remove everything in my local lede source tree and do a new rebuild
thank you for your patience Kuoruan

**Comment by kuoruan** [comment]
```
rm -rf /tmp
./scripts/feeds update -a
./scripts/feeds install -a
```

**Comment by jack338c** [comment]
ok,I will try and report you later

**Comment by jack338c** [comment]
this time I  remove everything and git clone https://git.lede-project.org/source.git for whole new make.
then copy everything about qos_gargoyle to my local lede source tree before making 
but it did not work

maybe I do missing something?

**Comment by kuoruan** [comment]
https://github.com/kuoruan/lede/commit/5f527aa1442007ad6e92f9812731508ff0b09830
This commit contains all files that changes.

**Comment by jack338c** [comment]
LEDE Reboot SNAPSHOT r4561-254f0da / LuCI Master (git-17.192.44320-00ae501)
Kernel Version | 4.4.74

maybe my lede is too new?

**Comment by kuoruan** [comment]
What is the error message?
I am using the newest source, do not have any problem.

**Comment by jack338c** [comment]
it still get unknown option "--todev" when I do "/etc/init.d/qos_gargoyle restart"

**Comment by kuoruan** [comment]
Where did you put the iptables patch?

**Comment by jack338c** [comment]
source/package/network/utils/iptables ( replace makefile  )

/home/jack/ledemaster/source/package/network/utils/iptables/patches(and copy 999-add-imq-support.patch )

**Comment by jack338c** [comment]
besides,I did a research on google
and found this http://jg192.f3322.net:82/wordpress/index.php/2017/01/18/lede%E7%BC%96%E8%AF%91qos_guoguo%E6%96%B9%E6%B3%95/
 it just like you said

**Comment by jack338c** [comment]
@kuoruan 
hi Kuoruan
I did not replace this file" include/netfilter.mk"  of [kuoruan/lede@5f527aa ](https://github.com/kuoruan/lede/commit/5f527aa1442007ad6e92f9812731508ff0b09830) before,it this need to be replaceed too?

**Comment by kuoruan** [comment]
Yes..

**Comment by jack338c** [comment]
Applying ./patches/001-musl-fixes.patch using plaintext: 
patching file Makefile
patching file qosmon.c
touch /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle/.prepared_cdc390166f36107930101e24457887f2_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.qos-gargoyle_installed
rm -f /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle/.configured_*
touch /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle/.built
touch /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle/.built_check
make -C /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle clean
make[4]: Entering directory '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle'
rm -rf *.o *~ .*sw* qosmon
make[4]: Leaving directory '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle'
make -C /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle AR="mips-openwrt-linux-musl-gcc-ar" AS="mips-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle:qos-gargoyle -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mips-openwrt-linux-musl-ld NM="mips-openwrt-linux-musl-gcc-nm" CC="mips-openwrt-linux-musl-gcc" GCC="mips-openwrt-linux-musl-gcc" CXX="mips-openwrt-linux-musl-g++" RANLIB="mips-openwrt-linux-musl-gcc-ranlib" STRIP=mips-openwrt-linux-musl-strip OBJCOPY=mips-openwrt-linux-musl-objcopy OBJDUMP=mips-openwrt-linux-musl-objdump SIZE=mips-openwrt-linux-musl-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle:qos-gargoyle -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I /home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/usr/include" LDFLAGS="-L/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/usr/lib -L/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/lib -L/home/jack/ledemaster/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl/usr/lib -L/home/jack/ledemaster/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl/lib -znow -zrelro -L /home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/usr/lib" BUILD_DIR="/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl" all
make[4]: Entering directory '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle'
mips-openwrt-linux-musl-gcc -D ONLYBG -D_GNU_SOURCE -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle:qos-gargoyle -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I /home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/usr/include -I /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full/iproute2-4.11.0 /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full/iproute2-4.4.0/include -I /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full/iproute2-4.11.0 /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full/iproute2-4.4.0/tc -c qosmon.c -o qosmon.o
qosmon.c:40:19: fatal error: utils.h: No such file or directory
compilation terminated.
Makefile:24: recipe for target 'qosmon.o' failed
make[4]: *** [qosmon.o] Error 1
make[4]: Leaving directory '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle'
Makefile:68: recipe for target '/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle/.built' failed
make[3]: *** [/home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/qos-gargoyle/.built] Error 2
make[3]: Leaving directory '/home/jack/ledemaster/source/package/qos-gargoyle'
package/Makefile:109: recipe for target 'package/qos-gargoyle/compile' failed
make[2]: *** [package/qos-gargoyle/compile] Error 2
make[2]: Leaving directory '/home/jack/ledemaster/source'
package/Makefile:105: recipe for target '/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/jack/ledemaster/source/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jack/ledemaster/source'
/home/jack/ledemaster/source/include/toplevel.mk:206: recipe for target 'world' failed
make: *** [world] Error 2


I just git clone the neweset gargoyle package and luci from your respository

**Comment by kuoruan** [comment]
```
rm -rf /home/jack/ledemaster/source/build_dir/target-mips_24kc_musl/iproute2-full
```

**Comment by jack338c** [comment]
you taught me before,Sorry..

**Comment by jack338c** [comment]
Success !
one more question,How to limit  a lan ip speed by luci-qos-gargoyle ? please help me
( I try to find the answer on Google,but no answer)

**Comment by jack338c** [comment]
or some tips,plesea...
