### ISSUE TITLE
石像鬼默认下不启动 应该怎样做啊

### ISSUE THREAD

**Issue by fuqiang03** [kuoruan/luci-app-qos-gargoyle#2]
石像鬼默认下不启动 应该怎样做啊

**Comment by kuoruan** [comment]
这个软件不是说直接可以用的，需要给内核打 imq 补丁。

**Comment by fuqiang03** [comment]
这些我都有
![qq 20170918130549](https://user-images.githubusercontent.com/26851715/30529657-37f227de-9c72-11e7-97a8-84fba4496abe.png)

**Comment by fuqiang03** [comment]
默认状态下我想让他处于关闭状态

**Comment by kuoruan** [comment]
禁用它就关掉了

**Comment by fuqiang03** [comment]
好的  大神什么时候能加入这个支持 

ipt-layer7 的支持

**Comment by kuoruan** [comment]
layer7 是故意去掉的，你可以装 ndpi，然后 luci 上就有选项了
https://github.com/kuoruan/lede-packages/tree/master/net/ndpi-netfilter

**Comment by fuqiang03** [comment]
谢谢

**Comment by fuqiang03** [comment]
gargoyle-packages  这个包大神更新了吗

**Comment by kuoruan** [comment]
没有更新，只是做了点代码的调整，最近我在尝试移植石像鬼的 流量配额。

**Comment by fuqiang03** [comment]
流量限制 不好玩

**Comment by kuoruan** [comment]
我刚刚改了改，现在带宽可以留空以单独禁用上传或者下载 QoS。

**Comment by fuqiang03** [comment]
imq 的王道

**Comment by fuqiang03** [comment]
有效果

**Comment by fuqiang03** [comment]
这会我编译了四次了

![qq 20170918141156](https://user-images.githubusercontent.com/26851715/30530728-cf0575aa-9c7b-11e7-8ad8-057f6a691b26.png)

**Comment by fuqiang03** [comment]
大神有空能把qos4的功能整合下就好了  毕竟原来都差不多

**Comment by kuoruan** [comment]
qosv4 的代码太乱了，而且会和石像鬼冲突，不想看

**Comment by baibihuiyi** [comment]
luci有bug啊,删除规则后其他规则全乱了

**Comment by fuqiang03** [comment]
![qq 20171112035402](https://user-images.githubusercontent.com/26851715/32692977-3635fa18-c75d-11e7-8cc7-4977efa143ce.png)
看看我的

**Comment by baibihuiyi** [comment]
修改qos-gargoyle下的Makefile
在$(eval $(call BuildPackage,qos-gargoyle))前面加入

define Package/qos-gargoyle/postinst
	#!/bin/sh
	$${IPKG_INSTROOT}/etc/init.d/qos_gargoyle stop 2>/dev/null
	$${IPKG_INSTROOT}/etc/init.d/qos_gargoyle disable 2>/dev/null
	exit 0
endef
默认就不启动

**Comment by fuqiang03** [comment]
@baibihuiyi  谢谢

**Comment by fuqiang03** [comment]
@baibihuiyi 
![qq 20171112134923](https://user-images.githubusercontent.com/26851715/32696319-6881f622-c7b0-11e7-80d3-253bc07f3569.png)

**Comment by baibihuiyi** [comment]
上面那个是安装ipk默认不启动的 如果编译的话就修改
luci-app-qos-gargoyle/root/etc/uci-defaults/40_luci-qos_gargoyle
#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qos_gargoyle[-1]
	add ucitrack qos_gargoyle
	set ucitrack.@qos_gargoyle[-1].init=qos_gargoyle
	commit ucitrack
EOF
/etc/init.d/qos_gargoyle stop
/etc/init.d/qos_gargoyle disable
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache
exit 0

**Comment by fuqiang03** [comment]
谢谢
