### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by fuqiang03** [kuoruan/luci-app-qos-gargoyle#3]
![qq 20170930004230](https://user-images.githubusercontent.com/26851715/31042901-b97cad08-a5e4-11e7-8296-56d0fe38dd4f.png)
![qq 20170930133756](https://user-images.githubusercontent.com/26851715/31042903-be6c82a2-a5e4-11e7-8900-1aa9b5ed4732.png)
wan口没有拨号的话 会出现错误
第一个图是日志产生的另一个错误

**Comment by kuoruan** [comment]
OK，我马上修复

**Comment by kuoruan** [comment]
已修复。
