### ISSUE TITLE
分类规则下的连接流量配置后和实际测试不相符

### ISSUE THREAD

**Issue by baibihuiyi** [kuoruan/luci-app-qos-gargoyle#4]
配置为10240k 也就是10M
实际测试1.3M就生效

**Comment by kuoruan** [comment]
仔细看了一下
https://github.com/kuoruan/gargoyle-packages/blob/master/qos-gargoyle/files/qos_gargoyle.init#L137
对应的会自动转换为 B，应该是没问题的
