### ISSUE TITLE
打开 启用 按钮显示以下问题

### ISSUE THREAD

**Issue by ntlf9t** [kuoruan/luci-app-qos-gargoyle#6]
/usr/lib/lua/luci/dispatcher.lua:500: Failed to execute firstchild dispatcher target for entry '/admin/network/qos_gargoyle'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:500: Failed to execute cbi dispatcher target for entry '/admin/network/qos_gargoyle/global'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:1350: attempt to concatenate local 'section' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:500: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

**Comment by kuoruan** [comment]
我今天做了个修改，忘了测了，你等一下，我看看

**Comment by kuoruan** [comment]
你把最新的那条 commit revert 了吧，然后在 qos_gargoyle 的配置文件上加一行
```
config global 'global'
```
我明天再来看这个问题

**Comment by ntlf9t** [comment]
明天再试☺
